### ISSUE TITLE
Cannot Use request action

### ISSUE THREAD

**Issue by EniMusguera** [anonyindian/gotgproto#17]
Code: https://pastebin.com/xMsVvqw4 < api and hash just examples. 
\context.go:174:14: cannot use request.Reaction

How can i fix it ?

**Comment by anonyindian** [comment]
Please describe the issue.

**Comment by EniMusguera** [comment]
> Please describe the issue. What were you trying to do, what did you use, etc.

Tonight I will describe bro. I'm
