### ISSUE TITLE
> Please describe the issue. What were you trying to do, what did you use, etc.

### ISSUE THREAD

**Issue by EniMusguera** [anonyindian/gotgproto#18]
> Tonight I will describe it in more detail.
I'm trying to log in, it looks like it's a session error.

(I accidentally closed the post)

**Comment by Dank-del** [comment]
What

**Comment by EniMusguera** [comment]
> What

go run main.go
# github.com/anonyindian/gotgproto/ext
..\..\..\..\go\pkg\mod\github.com\anonyindian\gotgproto@v1.0.0-beta08\ext\context.go:174:14: cannot use request.Reaction (variable of type []tg.ReactionClass) as type string in assignment

Code: https://pastebin.com/1cn9S1q6

**Comment by anonyindian** [comment]
It seems like you're using the latest version of Gotd, while gotgproto doesn't support it yet.
Execute the following command in the project root, it should fix the issue:
```bash
go get github.com/gotd/td@v0.67.0
```

**Comment by EniMusguera** [comment]
> It seems like you're using the latest version of Gotd, while gotgproto doesn't support it yet. Execute the following command in the project root, it should fix the issue:
> 
> ```shell
> go get github.com/gotd/td@v0.67.0
> ```

It worked. I'm new to Go. (I downloaded the pkg and threw it in the folder, because the Go get didn't work, if anyone has the same problem, just do that.

Thanks for your help!
